### ISSUE TITLE
Verify Api3ReaderProxyV1 contracts

### ISSUE THREAD

**Issue by hiletmis** [api3dao/contracts#228]
* Contracts that deployed by Api3ReaderProxyV1Factory are not verified automatically.

**To-Do**
* Verify example proxy contract on following chains:

- [x] apechain-arbitrum-sepolia-testnet
- [x] arbitrum
- [x] arbitrum-sepolia-testnet
- [x] astar
- [x] astar-sepolia-testnet
- [x] avalanche
- [x] avalanche-testnet
- [x] base
- [x] base-sepolia-testnet
- [x] berachain-testnet
- [ ] bitlayer (missing solidity 0.8.27 support)
- [ ] bitlayer-testnet (missing solidity 0.8.27 support)
- [x] blast
- [x] blast-sepolia-testnet
- [x] bob
- [x] bob-sepolia-testnet
- [x] bsc
- [x] bsc-testnet
- [x] camp-sepolia-testnet
- [x] conflux
- [x] conflux-testnet
- [ ] core (missing solidity 0.8.27 support)
- [ ] core-testnet (missing solidity 0.8.27 support)
- [x] ethereum
- [x] ethereum-holesky-testnet
- [x] ethereum-sepolia-testnet
- [x] fantom
- [ ] fantom-testnet
- [x] fraxtal
- [x] fraxtal-holesky-testnet
- [x] gnosis
- [x] gnosis-testnet
- [x] immutable-sepolia-testnet
- [x] inevm
- [x] inevm-testnet
- [ ] kava (missing solidity 0.8.27 support)
- [ ] kava-testnet
- [x] kroma
- [x] kroma-sepolia-testnet
- [x] lightlink
- [x] lightlink-sepolia-testnet
- [x] linea
- [x] linea-sepolia-testnet
- [x] lukso
- [x] lukso-testnet
- [x] lumia
- [x] lumia-sepolia-testnet
- [x] manta
- [x] manta-sepolia-testnet
- [x] mantle
- [x] mantle-sepolia-testnet
- [x] merlin
- [x] merlin-testnet
- [x] metal
- [x] metis
- [x] metis-sepolia-testnet
- [x] mode
- [x] mode-sepolia-testnet
- [x] moonbeam
- [x] moonbeam-testnet
- [x] moonriver
- [x] odyssey-sepolia-testnet
- [x] oev-network
- [x] opbnb
- [ ] opbnb-testnet
- [x] optimism
- [x] optimism-sepolia-testnet
- [x] polygon
- [x] polygon-sepolia-testnet
- [x] polygon-zkevm
- [x] polygon-zkevm-sepolia-testnet
- [x] rari
- [x] rari-arbitrum-sepolia-testnet
- [x] scroll
- [x] scroll-sepolia-testnet
- [ ] sei
- [ ] sei-testnet
- [x] soneium-sepolia-testnet
- [ ] sonic-testnet
- [x] taiko
- [x] taiko-holesky-testnet
- [x] unichain-sepolia-testnet
- [x] x-layer
- [x] x-layer-sepolia-testnet
- [x] zircuit
- [x] zircuit-sepolia-testnet

**Comment by hiletmis** [comment]
@bbenligiray the remaining chains will be completed when [this task](https://github.com/api3dao/contracts/issues/225) is completed.
